Upgrade nbconvert
jupyter/nbviewer pull request #1015
Opened 2022-08-11 08:22 UTC by martinRenou

Revive https://github.com/jupyter/nbviewer/pull/1003 and merge with https://github.com/jupyter/nbviewer/pull/1014

2022-08-22 13:53 UTC, minrk commented
@martinRenou this mostly works now, but the lab template's font-awesome 5 is conflicting with the font-awesome 4 used on the nbviewer page, erasing the icons:

![Screen Shot 2022-08-22 at 14 47 05](https://user-images.githubusercontent.com/151929/185937516-10421d1c-a459-4505-a70a-b02ff6210584.png)
 
Not sure if there's a simple fix for that.

2022-08-22 14:07 UTC, martinRenou commented
Thanks a lot for pushing on this @minrk !

> but the lab template's font-awesome 5 is conflicting with the font-awesome 4 used on the nbviewer page, erasing the icons:

In Voila we do the following, maybe that will fix the nbviewer case:

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@^5/css/all.min.css" type="text/css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@^5/css/v4-shims.min.css" type="text/css" />
```

I am not sure where to add this though. I wonder if this should go directly in nbconvert.

2022-08-24 10:41 UTC, minrk commented
We should update to fa5, but this backward-incompatibility is definitely an issue. The shims do work in layout.html (after our own css), but result in a different size than before:

before:
<img width="475" alt="Screen Shot 2022-08-24 at 12 39 30" src="https://user-images.githubusercontent.com/151929/186398649-4b2542a1-00cb-4262-a87c-239aa560e648.png">

after:
<img width="546" alt="Screen Shot 2022-08-24 at 12 39 27" src="https://user-images.githubusercontent.com/151929/186398665-67e51c65-5c93-4b00-8fc8-06fd95bd1dbe.png">

2022-10-31 08:32 UTC, Carreau commented
The navbar seem to be missing visually as well.
<img width="424" alt="Screen Shot 2022-10-31 at 09 31 59" src="https://user-images.githubusercontent.com/335567/198965319-5dece69e-a3ce-4052-bbef-b049e48083d6.png">

2022-10-31 08:33 UTC, Carreau commented on nbviewer/templates/notebook.html
> +    BREAKCRUMB
DEBUG ?

2022-10-31 09:19 UTC, Carreau commented
A huge chink of the css issue seem to be with

```
  {% block ipywidgets %}
    <!-- block ipywidgets notebook.html -->
    <script>
      (function() {
        function addWidgetsRenderer() {
          var mimeElement = document.querySelector('script[type="application/vnd.jupyter.widget-view+json"]');
          var scriptElement = document.createElement('script');
          var widgetRendererSrc = '{{ ipywidgets_base_url }}@jupyter-widgets/html-manager@{{ jupyter_widgets_html_manager_version }}/dist/embed-amd.js';
          var widgetState;

          try {
            widgetState = mimeElement && JSON.parse(mimeElement.innerHTML);

            if (widgetState && (widgetState.version_major < 2 || !widgetState.version_major)) {
              widgetRendererSrc = '{{ ipywidgets_base_url }}jupyter-js-widgets@{{ jupyter_js_widgets_version }}/dist/embed.js';
            }
          } catch(e) {}

          scriptElement.src = widgetRendererSrc;
          document.body.appendChild(scriptElement);
        }

        document.addEventListener('DOMContentLoaded', addWidgetsRenderer);
      }());
    </script>
    <!-- end block ipywidgets notebook.html -->
  {% endblock ipywidgets %}
```

That dynamically inject css.

2022-10-31 12:34 UTC, minrk commented on nbviewer/templates/notebook.html
> +    BREAKCRUMB
yes, debugging

2022-10-31 12:34 UTC, minrk commented
@Carreau thanks for picking this up!

2022-10-31 14:23 UTC, Carreau commented on README.md
> +$ python -m nbviewer --debug --no-cache --host=127.0.0.1
I think listening on 0.0.0.0 by default is a security problem. Well, here on macos, it present me from doing so without root access so It's ok-ish, but i'd like to fix it.

2022-10-31 14:29 UTC, Carreau requested changes
Slides are also quite broken. 

For example you can compare with  https://nbviewer.org/format/slides/github/astrojuanlu/talk-dataframes/blob/main/slides.ipynb

2022-10-31 15:15 UTC, Carreau commented
Most of the reveal issue seem to be coming down to font-size being way to big. 

Something like the following in the right place make it bearable.
```
div.reveal {
    font-size: 10px;

}
```

Now we do seem to have 2 sets of reveal controls on the page if you look carefully: 

<img width="94" alt="Screen Shot 2022-10-31 at 16 15 10" src="https://user-images.githubusercontent.com/335567/199042780-2f5f8390-a670-4a46-b4d9-4644e9a4baf1.png">

2022-11-01 09:36 UTC, Carreau commented
So there are indeed 2 reveal. One done by nbconvert, and one by nbviewer. 

Really this is crazy that we are embedding a full nbconvert with `body|safe`, that even include DOCTYPE ????. And of course the Reveal from nbconvert has no hooks, so we can't listen to the slide change event to hide the the nbviewer header.

The new nbconverts are really backward in term of reusing the templates...

2022-11-01 10:03 UTC, Carreau approved these changes

2022-11-01 10:04 UTC, Carreau commented on nbviewer/providers/github/handlers.py
> +
```suggestion
```

2022-11-01 10:04 UTC, Carreau commented on nbviewer/templates/formats/slides.html
> -          $('#menubar').headroom((!idx.h && !idx.v) ? 'pin' : 'unpin');
That is the part we can't do without changes to nbviewer.

2022-11-01 10:06 UTC, Carreau approved these changes
I think that's about as far as I we can reasonably take it in a single PR. It works, but there is still alot of work to do.

2022-11-07 09:08 UTC, Carreau commented
I think we should leapfrog nbconvert 6.x and go directly to 7.x, I'm going to create a 1.x branch that is the current main, and suggest main become 2.x.

2022-11-07 09:39 UTC, minrk commented
If that makes it easier, by all means!

2022-11-07 09:54 UTC, Carreau commented
> If that makes it easier, by all means!

It's more on the communication side, there will be likely so much change between 1.x and main, that it does make sens to bump major version number. This also let us re-do a 1.x at one point if ever necessary. 

I've push a 1.x branch, and I'm going to merge this and keep iterating, once this is merged, main should not be considered stable as a number of notebook likely won't render yet, and reveal is still partially broken .

2022-11-07 09:55 UTC, merged

2022-11-07 10:05 UTC, martinRenou commented
Thanks a lot for pushing on this!

2024-11-16 15:51 UTC, mgeier commented
Would it be possible to get another `nbconvert` upgrade on https://nbviewer.org/?

I think the latest release should fix an issue where SVG images are not displayed correctly: https://github.com/jupyter/nbconvert/issues/1863.
See also #1037.